print("Dear User Welcome to your Python Calculator")
A = input("Please enter your desired number: ")
B = input('Please enter your another desired number which should not be equal to 0: ')
print("Addition Result")
print(int(A)+int(B))
print("Subtraction Result")
print(int(A)-int(B))
print("Multiplication Result")
print(int(A)*int(B))
print("Division Result")
print(int(A)/int(B))
print("Thank You for using Python Calculator. See You Later!")